### ISSUE TITLE
aioftp 0.17 was Python 3.7+

### ISSUE THREAD

**Issue by Cadair** [conda-forge/aioftp-feedstock#10]
The recipe for 0.17(+) is still built for 3.6 when upstream dropped support for it.

**Comment by nabobalis** [comment]
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/101 fixes the existing packages. 

https://github.com/conda-forge/aioftp-feedstock/pull/12 fixes the current recipe.
